/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const MemberStatus = IDL.Variant({
  'active' : IDL.Null,
  'inactive' : IDL.Null,
});
export const Time = IDL.Int;
export const Member = IDL.Record({
  'id' : IDL.Nat,
  'status' : MemberStatus,
  'contact' : IDL.Text,
  'planId' : IDL.Opt(IDL.Nat),
  'name' : IDL.Text,
  'createdAt' : Time,
  'membershipStart' : IDL.Opt(Time),
  'updatedAt' : Time,
  'membershipEnd' : IDL.Opt(Time),
});
export const UserProfile = IDL.Record({
  'memberId' : IDL.Opt(IDL.Nat),
  'name' : IDL.Text,
});
export const CheckIn = IDL.Record({
  'id' : IDL.Nat,
  'memberId' : IDL.Nat,
  'timestamp' : Time,
});
export const Payment = IDL.Record({
  'id' : IDL.Nat,
  'memberId' : IDL.Nat,
  'method' : IDL.Text,
  'date' : Time,
  'notes' : IDL.Text,
  'amount' : IDL.Float64,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addPayment' : IDL.Func(
      [IDL.Nat, IDL.Float64, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'checkIn' : IDL.Func([IDL.Nat], [IDL.Nat], []),
  'createMember' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
  'getAllMembers' : IDL.Func([], [IDL.Vec(Member)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCheckInsForMember' : IDL.Func([IDL.Nat], [IDL.Vec(CheckIn)], ['query']),
  'getMember' : IDL.Func([IDL.Nat], [Member], ['query']),
  'getPaymentsForMember' : IDL.Func([IDL.Nat], [IDL.Vec(Payment)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'linkPrincipalToMember' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateMember' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const MemberStatus = IDL.Variant({
    'active' : IDL.Null,
    'inactive' : IDL.Null,
  });
  const Time = IDL.Int;
  const Member = IDL.Record({
    'id' : IDL.Nat,
    'status' : MemberStatus,
    'contact' : IDL.Text,
    'planId' : IDL.Opt(IDL.Nat),
    'name' : IDL.Text,
    'createdAt' : Time,
    'membershipStart' : IDL.Opt(Time),
    'updatedAt' : Time,
    'membershipEnd' : IDL.Opt(Time),
  });
  const UserProfile = IDL.Record({
    'memberId' : IDL.Opt(IDL.Nat),
    'name' : IDL.Text,
  });
  const CheckIn = IDL.Record({
    'id' : IDL.Nat,
    'memberId' : IDL.Nat,
    'timestamp' : Time,
  });
  const Payment = IDL.Record({
    'id' : IDL.Nat,
    'memberId' : IDL.Nat,
    'method' : IDL.Text,
    'date' : Time,
    'notes' : IDL.Text,
    'amount' : IDL.Float64,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addPayment' : IDL.Func(
        [IDL.Nat, IDL.Float64, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'checkIn' : IDL.Func([IDL.Nat], [IDL.Nat], []),
    'createMember' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
    'getAllMembers' : IDL.Func([], [IDL.Vec(Member)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCheckInsForMember' : IDL.Func([IDL.Nat], [IDL.Vec(CheckIn)], ['query']),
    'getMember' : IDL.Func([IDL.Nat], [Member], ['query']),
    'getPaymentsForMember' : IDL.Func([IDL.Nat], [IDL.Vec(Payment)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'linkPrincipalToMember' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateMember' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };