/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CheckIn {
  'id' : bigint,
  'memberId' : bigint,
  'timestamp' : Time,
}
export interface Member {
  'id' : bigint,
  'status' : MemberStatus,
  'contact' : string,
  'planId' : [] | [bigint],
  'name' : string,
  'createdAt' : Time,
  'membershipStart' : [] | [Time],
  'updatedAt' : Time,
  'membershipEnd' : [] | [Time],
}
export type MemberStatus = { 'active' : null } |
  { 'inactive' : null };
export interface Payment {
  'id' : bigint,
  'memberId' : bigint,
  'method' : string,
  'date' : Time,
  'notes' : string,
  'amount' : number,
}
export type Time = bigint;
export interface UserProfile { 'memberId' : [] | [bigint], 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addPayment' : ActorMethod<[bigint, number, string, string], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'checkIn' : ActorMethod<[bigint], bigint>,
  'createMember' : ActorMethod<[string, string], bigint>,
  'getAllMembers' : ActorMethod<[], Array<Member>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCheckInsForMember' : ActorMethod<[bigint], Array<CheckIn>>,
  'getMember' : ActorMethod<[bigint], Member>,
  'getPaymentsForMember' : ActorMethod<[bigint], Array<Payment>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'linkPrincipalToMember' : ActorMethod<[Principal, bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateMember' : ActorMethod<[bigint, string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];